In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st
import plotly.express as px

In [ ]:
df = pd.read_csv(r"C:\Users\sachi\OneDrive\temp\transformed_company_data.csv")

,Company,Company Path,Industry,Country,employees,marketcap,revenue,earnings,operating-margin,total-assets,total-liabilities,total-debt,net-assets,pe-ratio,ps-ratio
0,Amazon,https://companiesmarketcap.com/amazon,Technology,USA,1500000,1.966000e+12,5.747800e+11,4.073000e+10,-0.0115,5.278500e+11,3.259700e+11,1.356100e+11,2.018700e+11,96.50,3.4200
1,Foxconn (Hon Hai Precision Industry),https://companiesmarketcap.com/foxconn,Technology,Taiwan,826608,6.475000e+10,1.983200e+11,6.160000e+09,0.0255,1.284000e+11,7.344000e+10,3.073000e+10,5.495000e+10,16.10,0.3255
2,Jingdong Mall,https://companiesmarketcap.com/jingdong-mall,Technology,China,450679,4.250000e+10,1.524800e+11,4.910000e+09,0.0255,8.618000e+10,4.482000e+10,9.750000e+09,4.135000e+10,13.70,0.2839
3,IBM,https://companiesmarketcap.com/ibm,Technology,USA,288300,1.704200e+11,6.185000e+10,8.690000e+09,0.0308,1.352400e+11,1.126200e+11,5.993000e+10,2.261000e+10,24.40,2.7600
4,Panasonic,https://companiesmarketcap.com/panasonic,Technology,Japan,232527,2.153000e+10,5.964000e+10,3.170000e+09,0.0487,6.321000e+10,3.229000e+10,1.130000e+10,3.092000e+10,7.18,0.3597

In [40]:
df.describe()

,employees,marketcap,revenue,earnings,operating-margin,total-assets,total-liabilities,total-debt,net-assets,pe-ratio,ps-ratio
count,1.500000e+03,1.497000e+03,1.499000e+03,1.498000e+03,1305.000000,1.499000e+03,1.499000e+03,1.486000e+03,1.497000e+03,1454.000000,1483.000000
mean,3.110677e+04,3.405215e+10,1.719062e+10,1.984197e+09,-1.224687,3.622088e+10,2.612129e+10,7.104073e+09,1.010865e+10,14.467366,3.237282
std,9.764210e+04,1.702847e+11,4.840570e+10,9.152037e+09,40.876076,9.466575e+10,8.056601e+10,1.478049e+10,2.563455e+10,78.322635,5.947946
min,0.000000e+00,7.000000e+04,-3.931000e+10,-1.367000e+10,-1474.050000,2.000000e+06,1.970000e+06,1.000000e+04,-1.515000e+10,-837.000000,-0.099900
25%,2.235250e+03,1.780000e+09,1.155000e+09,4.225000e+07,0.019500,2.360000e+09,1.230000e+09,4.400000e+08,8.700000e+08,4.590000,0.649250
50%,8.518000e+03,5.770000e+09,4.140000e+09,3.500000e+08,0.087400,8.110000e+09,4.560000e+09,2.095000e+09,2.920000e+09,13.750000,1.540000
75%,2.437500e+04,1.878000e+10,1.307500e+10,1.360000e+09,0.173800,2.734500e+10,1.530500e+10,6.357500e+09,9.240000e+09,26.300000,3.530000
max,2.100000e+06,3.179000e+12,6.481200e+11,2.369600e+11,1.938600,1.638000e+12,1.464000e+12,2.105200e+11,4.637800e+11,901.000000,108.000000

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1500 non-null   str
 1   Company Path       1500 non-null   str
 2   Industry           1500 non-null   str
 3   Country            1499 non-null   str
 4   employees          1500 non-null   int64
 5   marketcap          1497 non-null   float64
 6   revenue            1499 non-null   float64
 7   earnings           1498 non-null   float64
 8   operating-margin   1305 non-null   float64
 9   total-assets       1499 non-null   float64
 10  total-liabilities  1499 non-null   float64
 11  total-debt         1486 non-null   float64
 12  net-assets         1497 non-null   float64
 13  pe-ratio           1454 non-null   float64
 14  ps-ratio           1483 non-null   float64
dtypes: float64(10), int64(1), str(4)
memory usage: 175.9 KB

In [42]:
len(df.columns)

15

In [43]:
df = df.drop(columns=['Company Path'])

In [32]:
import sys, subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "plotly"])

0

In [ ]:
#Plotting a KPI card for each company 

df_revenue_kpi = df.set_index('Company')['revenue'].to_dict()
cols = st.columns(15) 

for i in range(15):
    company = list(df_revenue_kpi.keys())[i]    # company name
    revenue = list(df_revenue_kpi.values())[i]  # revenue value
    
    cols[i].metric(
        label=f"{company} Total Revenue", 
        value=f"${revenue:,}",  
        delta="+12%", 
        border=True
    )

KeyError: 1

In [31]:
df.columns

Index(['Company', 'Industry', 'Country', 'employees', 'marketcap', 'revenue',
       'earnings', 'operating-margin', 'total-assets', 'total-liabilities',
       'total-debt', 'net-assets', 'pe-ratio', 'ps-ratio'],
      dtype='str')

In [ ]:
# Plotting scatter plot to display operating-margin(%) vs market cap
df['operating-margin'] = df['operating-margin']*100
st.scatter_chart(df, x=df['operating-margin'], y=df['marketcap'])

In [ ]:
# Creating a Tree map to show the size of Industry by Revenue. 
fig = px.treemap(df, path=["Industry"], values="revenue")
st.plotly_chart(fig, use_container_width=True)

In [46]:
df['revenue'].isna().sum()

np.int64(1)